package com.inventory.util;

import com.inventory.exception.DatabaseException;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Central place that knows HOW to reach the database.
 *
 * Every DAO calls getConnection(), so switching to MySQL later means changing
 * only the URL here (plus the driver dependency and AUTOINCREMENT in schema.sql).
 *
 * A fresh connection is opened per operation. SQLite connections are cheap and
 * this is a single-user console app, so a connection pool would be over-engineering.
 * Callers must close the connection (try-with-resources).
 */
public final class DBConnection {

    /** Override with -Dinventory.db.url=jdbc:sqlite:/some/path.db (used by tests). */
    private static final String DB_URL =
            System.getProperty("inventory.db.url", "jdbc:sqlite:inventory.db");

    private static final String SCHEMA_RESOURCE = "/schema.sql";

    private DBConnection() {
        // utility class - no instances
    }

    /**
     * Opens a new connection with foreign-key enforcement switched on.
     * SQLite ignores FOREIGN KEY constraints by default and the setting is
     * per-connection, so it has to be enabled every time a connection is opened.
     */
    public static Connection getConnection() throws SQLException {
        Connection connection = DriverManager.getConnection(DB_URL);
        try (Statement statement = connection.createStatement()) {
            statement.execute("PRAGMA foreign_keys = ON");
        } catch (SQLException e) {
            connection.close();
            throw e;
        }
        return connection;
    }

    /**
     * Returns the id generated by the most recent INSERT on THIS connection.
     *
     * We use SQLite's last_insert_rowid() instead of JDBC's getGeneratedKeys()
     * because getGeneratedKeys() is not supported by every sqlite-jdbc version.
     * This is the one database-specific detail of id retrieval, so it is kept here
     * (for MySQL it would be LAST_INSERT_ID(), or plain getGeneratedKeys()).
     * Call it right after the INSERT, on the same connection.
     */
    public static int lastInsertId(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT last_insert_rowid()")) {
            if (!rs.next()) {
                throw new SQLException("Could not read the generated id");
            }
            return rs.getInt(1);
        }
    }

    /**
     * Creates the tables and loads the sample data the first time the app runs
     * (detected by the absence of the users table). Safe to call on every start-up.
     */
    public static void initializeDatabase() {
        try (Connection connection = getConnection()) {
            if (tableExists(connection, "users")) {
                return;
            }
            runSchemaScript(connection);
        } catch (SQLException e) {
            throw new DatabaseException("Could not initialise the database: " + e.getMessage(), e);
        }
    }

    private static boolean tableExists(Connection connection, String tableName) throws SQLException {
        String sql = "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?";
        try (var statement = connection.prepareStatement(sql)) {
            statement.setString(1, tableName);
            try (ResultSet rs = statement.executeQuery()) {
                return rs.next();
            }
        }
    }

    /** Reads schema.sql from the classpath and executes it one statement at a time, atomically. */
    private static void runSchemaScript(Connection connection) throws SQLException {
        String script = readSchemaResource();
        boolean previousAutoCommit = connection.getAutoCommit();
        connection.setAutoCommit(false);
        try (Statement statement = connection.createStatement()) {
            for (String sql : splitStatements(script)) {
                statement.execute(sql);
            }
            connection.commit();
        } catch (SQLException e) {
            connection.rollback();
            throw e;
        } finally {
            connection.setAutoCommit(previousAutoCommit);
        }
    }

    private static String readSchemaResource() {
        try (InputStream in = DBConnection.class.getResourceAsStream(SCHEMA_RESOURCE)) {
            if (in == null) {
                throw new DatabaseException("schema.sql not found on the classpath", null);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new DatabaseException("Could not read schema.sql: " + e.getMessage(), e);
        }
    }

    /**
     * Strips "-- ..." comments, then splits on ';'. This is deliberately simple:
     * it is correct for our schema.sql, which has no ';' or '--' inside string literals.
     */
    static java.util.List<String> splitStatements(String script) {
        StringBuilder withoutComments = new StringBuilder();
        for (String line : script.split("\\R")) {
            int commentStart = line.indexOf("--");
            withoutComments.append(commentStart >= 0 ? line.substring(0, commentStart) : line).append('\n');
        }
        java.util.List<String> statements = new java.util.ArrayList<>();
        for (String part : withoutComments.toString().split(";")) {
            if (!part.isBlank()) {
                statements.add(part.trim());
            }
        }
        return statements;
    }
}
